stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ECS_CLUSTER_NAME: Nodejs-ecs
  AWS_ECS_SERVICE_NAME: nodejs-service
  AWS_ECR_REPOSITORY: nodejs-ecs

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
    - zip -r dist.zip dist/

  artifacts:
    paths:
    - dist.zip

deploy:
  stage: deploy
  image: amazon/aws-cli:2.x
  before_script:
    - echo "Logging into Amazon ECR..."
    - echo "$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY" | aws configure --profile ecsuser
  script:
    - aws s3 cp dist.zip s3://nodejs-git/
    - aws ecs update-service --cluster $AWS_ECS_CLUSTER_NAME --service $AWS_ECS_SERVICE_NAME --force-new-deployment

