stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ECS_CLUSTER_NAME: Nodejs-ecs
  AWS_ECS_SERVICE_NAME: nodejs-service
  AWS_ECR_REPOSITORY: nodejs-ecs

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build

  artifacts:
    paths:
    - dist/
    - package-lock.json
    - node_modules/

deploy:
  stage: deploy
  image: amazon/aws-cli:2.x
  before_script:
    - echo "Logging into Amazon ECR..."
    - echo "$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY" | aws configure --profile ecsuser
  script:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - docker build -t $AWS_ECR_REPOSITORY .
    - docker tag $AWS_ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_ECR_REPOSITORY:latest
    - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_ECR_REPOSITORY:latest
    - aws ecs update-service --cluster $AWS_ECS_CLUSTER_NAME --service $AWS_ECS_SERVICE_NAME --force-new-deployment

